spring.application.name=job-async
server.port=${PORT}
spring.main.banner-mode=off
server.error.include-stacktrace=never


#--- datasource
spring.datasource.url=jdbc:postgresql://localhost:15432/sdi?currentSchema=fwnet
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PW}
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true

#spring.jpa.hibernate.ddl-auto=none # gestionado por schema.sql

#--- logging
#logging.level.root=DEBUG
#logging.level.dev.jacr=ERROR
#logging.level.org.jobrunr=DEBUG

#--- jobrunr
org.jobrunr.background-job-server.enabled=true
org.jobrunr.dashboard.enabled=true
org.jobrunr.dashboard.port=8000
org.jobrunr.database.type=sql
#org.jobrunr.database.datasource.url=jdbc:postgresql://localhost:15432/sdi?currentSchema=fwnet
org.jobrunr.database.datasource.username=${DB_USER}
org.jobrunr.database.datasource.password=${DB_PW}

