spring.application.name=job-async
server.port=${PORT}
spring.main.banner-mode=off
server.error.include-stacktrace=never

#--- datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PW}
spring.jpa.hibernate.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

#spring.jpa.hibernate.ddl-auto=none # gestionado por schema.sql

#--- logging
#logging.level.root=DEBUG
#logging.level.dev.jacr=ERROR
#logging.level.org.jobrunr=DEBUG

#--- jobrunr
org.jobrunr.background-job-server.enabled=true
org.jobrunr.dashboard.enabled=true
org.jobrunr.dashboard.port=${JOBRUNR_DASHBOARD_PORT}
org.jobrunr.database.type=sql
org.jobrunr.database.datasource.url=${JOBRUNR_DATASOURCE_URL}
org.jobrunr.database.datasource.username=${DB_USER}
org.jobrunr.database.datasource.password=${DB_PW}

